"""
Qwen3-TTS Nodes for ComfyUI.
Exports all node classes and their mappings.
"""

from .model_loader import (
    Qwen3TTSModelLoader,
    Qwen3TTSModelWrapper,
    NODE_CLASS_MAPPINGS as LOADER_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LOADER_DISPLAY_MAPPINGS,
)

from .custom_voice import (
    Qwen3TTSCustomVoice,
    NODE_CLASS_MAPPINGS as CUSTOM_VOICE_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CUSTOM_VOICE_DISPLAY_MAPPINGS,
)

from .voice_design import (
    Qwen3TTSVoiceDesign,
    NODE_CLASS_MAPPINGS as VOICE_DESIGN_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as VOICE_DESIGN_DISPLAY_MAPPINGS,
)

from .voice_clone import (
    Qwen3TTSVoiceClone,
    NODE_CLASS_MAPPINGS as VOICE_CLONE_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as VOICE_CLONE_DISPLAY_MAPPINGS,
)

# Combine all node mappings
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(LOADER_MAPPINGS)
NODE_CLASS_MAPPINGS.update(CUSTOM_VOICE_MAPPINGS)
NODE_CLASS_MAPPINGS.update(VOICE_DESIGN_MAPPINGS)
NODE_CLASS_MAPPINGS.update(VOICE_CLONE_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(LOADER_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(CUSTOM_VOICE_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(VOICE_DESIGN_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(VOICE_CLONE_DISPLAY_MAPPINGS)

__all__ = [
    "Qwen3TTSModelLoader",
    "Qwen3TTSModelWrapper",
    "Qwen3TTSCustomVoice",
    "Qwen3TTSVoiceDesign",
    "Qwen3TTSVoiceClone",
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
]
